dist: xenial
sudo: true
language: perl
perl:
  - "5.22"
  - "5.24"
  - "5.24-shrplib"
  - "5.26"
  - "5.26-shrplib"
  - "5.28"
services:
  - mysql
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5072E1F5
  - echo "deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-tools" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libmysqlcppconn-dev -y
  - mysql -e "INSTALL PLUGIN mysqlx SONAME 'mysqlx.so'"
install:
  - cpanm --quiet --notest --skip-satisfied DBI Devel::CheckLib
  - cpanm --verbose --installdeps --notest .
script:
  - perl Makefile.PL
  - make disttest
